### ISSUE TITLE
appendornot useful PKG-  Suggestion: set "create_subfolders" default = FALSE.

### ISSUE THREAD

**Issue by sfd99** [favstats/appendornot#1]
**Hi Fabio,**

appendornot:
Simple to use 
and useful PKG - thanks!.

>  save_lines(names(mtcars), "carnames.txt")
Error in save_lines(names(mtcars), "carnames.txt") : 
  argument "create_subfolders" is missing, with no default

>  save_lines(names(mtcars), "carnames.txt", F)
   then it works OK...

**My (strong) suggestion:** 
(if I may... )

In _BOTH_ functions,
  save_csv() 
     and in 
  save_lines(),

make the default argument "create_subfolders" 
**= FALSE as a DEFAULT.**
(instead of  the current "TRUE"...).

I believe that
this is a more _natural workflow_.
ie: 
add a = TRUE argument
to a Function,
only for additional functionality:
"create or use a subfolder to save...".

Fabio,
just my point of view,
thanks for the nice PKG!. 

**SFd99
San Francisco
Latest UBUNTU Linux 20.04
Rstudio
appendornot PKG v: 0.0.0.9900**

**Comment by favstats** [comment]
Thank you for suggestion! I have changed this in a recent commit, per your suggestion: https://github.com/favstats/appendornot/commit/94097531ad01a11cc009d5b6ffe4ff6c352b79a9

thank you!
